# Generated by Django 3.1.2 on 2021-03-19 19:40

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('updated_ts', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EducationCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('updated_ts', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('updated_ts', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HobbyCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('updated_ts', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MotherTongue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('updated_ts', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OccupationCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('updated_ts', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Raasi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('updated_ts', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Religion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('updated_ts', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('updated_ts', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCaste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('updated_ts', models.DateTimeField(auto_now=True)),
                ('caste', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.caste')),
                ('religion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.religion')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.CharField(max_length=500)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=20)),
                ('about_me', models.TextField()),
                ('about', models.TextField()),
                ('about_family', models.TextField()),
                ('dob', models.DateTimeField()),
                ('body_type', models.CharField(choices=[('Average', 'Average'), ('Athletic', 'Athletic'), ('Slim', 'Slim'), ('Heavy', 'Heavy')], default='Average', max_length=20)),
                ('physical_status', models.CharField(choices=[('Normal', 'Normal'), ('Physically Challenged', 'Physically Challenged')], default='Normal', max_length=25)),
                ('eating_habits', models.CharField(choices=[('Vegetarian', 'Vegetarian'), ('Non-Vegetarian', 'Non-Vegetarian'), ('Eggetarian', 'Eggetarian')], default='Vegetarian', max_length=20)),
                ('drinking_habits', models.CharField(choices=[('No', 'No'), ('Yes', 'Yes'), ('Occasionally', 'Occasionally')], default='No', max_length=20)),
                ('smoking_habits', models.CharField(choices=[('No', 'No'), ('Yes', 'Yes'), ('Occasionally', 'Occasionally')], default='No', max_length=20)),
                ('profile_created_by', models.CharField(choices=[('Self', 'Self'), ('Parent', 'Parent'), ('Sibling', 'Sibling'), ('Friend', 'Friend'), ('Relative', 'Relative')], default='Self', max_length=20)),
                ('height', models.DecimalField(decimal_places=2, max_digits=2)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=2)),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('work_location', models.CharField(max_length=50)),
                ('native_location', models.CharField(max_length=50)),
                ('primary_phone', models.CharField(max_length=20)),
                ('secondary_phone', models.CharField(max_length=20)),
                ('gothram', models.CharField(max_length=20)),
                ('dosham', models.CharField(max_length=20)),
                ('zodiac', models.CharField(max_length=20)),
                ('horoscope', models.FileField(upload_to=api.models.user_horoscope_path)),
                ('college', models.CharField(max_length=50)),
                ('employed_in', models.CharField(choices=[('Private', 'Private'), ('Business', 'Business'), ('Not Working', 'Not Working'), ('Government/PSU', 'Government/PSU'), ('Defence', 'Defence'), ('Self Employed', 'Self Employed')], default='Private', max_length=50)),
                ('salary_per_month', models.DecimalField(decimal_places=2, max_digits=15)),
                ('salary_currency_type', models.CharField(max_length=10)),
                ('email_verified', models.BooleanField(default=False)),
                ('phone_verified', models.BooleanField(default=False)),
                ('completed_basic_details', models.BooleanField(default=False)),
                ('completed_relegious_details', models.BooleanField(default=False)),
                ('completed_professional_details', models.BooleanField(default=False)),
                ('completed_family_details', models.BooleanField(default=False)),
                ('completed_profile_details', models.BooleanField(default=False)),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('updated_ts', models.DateTimeField(auto_now=True)),
                ('caste', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.caste')),
                ('highest_education', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.educationcategory')),
                ('mother_tongue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.mothertongue')),
                ('occupation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.occupationcategory')),
                ('religion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.religion')),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.star')),
                ('sub_caste', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.subcaste')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to=api.models.user_directory_path)),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('updated_ts', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserHobby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('updated_ts', models.DateTimeField(auto_now=True)),
                ('hobby', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.hobby')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserFamily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=40)),
                ('is_employed', models.BooleanField(max_length=40)),
                ('occupation', models.CharField(max_length=40)),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('updated_ts', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RequestLogger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=10)),
                ('request_path', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PartnerPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_from', models.IntegerField()),
                ('age_to', models.IntegerField()),
                ('height_from', models.DecimalField(decimal_places=2, max_digits=2)),
                ('height_to', models.DecimalField(decimal_places=2, max_digits=2)),
                ('physical_status', models.CharField(choices=[('Normal', 'Normal'), ('Physically Challenged', 'Physically Challenged')], default='Normal', max_length=25)),
                ('body_type', models.CharField(choices=[('Average', 'Average'), ('Athletic', 'Athletic'), ('Slim', 'Slim'), ('Heavy', 'Heavy')], default='Average', max_length=10)),
                ('eating_habits', models.CharField(choices=[('Vegetarian', 'Vegetarian'), ('Non-Vegetarian', 'Non-Vegetarian'), ('Eggetarian', 'Eggetarian')], default='Vegetarian', max_length=20)),
                ('drinking_habits', models.CharField(choices=[('No', 'No'), ('Yes', 'Yes'), ('Occasionally', 'Occasionally')], default='No', max_length=20)),
                ('smoking_habits', models.CharField(choices=[('No', 'No'), ('Yes', 'Yes'), ('Occasionally', 'Occasionally')], default='No', max_length=20)),
                ('employed_in', models.CharField(choices=[('Private', 'Private'), ('Business', 'Business'), ('Not Working', 'Not Working'), ('Government/PSU', 'Government/PSU'), ('Defence', 'Defence'), ('Self Employed', 'Self Employed')], default='Private', max_length=50)),
                ('income_from', models.IntegerField()),
                ('income_to', models.IntegerField()),
                ('dosham', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ("Doesn't Mater", "Doesn't Mater")], default='No', max_length=20)),
                ('about_partner', models.TextField()),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('updated_ts', models.DateTimeField(auto_now=True)),
                ('caste', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.caste')),
                ('highest_education', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.educationcategory')),
                ('mother_tongue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.mothertongue')),
                ('occupation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.occupationcategory')),
                ('raasi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.raasi')),
                ('religion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.religion')),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.star')),
                ('sub_caste', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.subcaste')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('notification_type', models.CharField(max_length=40)),
                ('status', models.CharField(max_length=40)),
                ('link', models.CharField(max_length=40)),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('updated_ts', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership', models.CharField(max_length=40)),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('updated_ts', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='hobby',
            name='hobby_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.hobbycategory'),
        ),
        migrations.AddField(
            model_name='caste',
            name='religion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.religion'),
        ),
    ]
