# Generated by Django 3.1.2 on 2021-03-21 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210321_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(blank=True, max_length=50, null=True)),
                ('device_token', models.CharField(blank=True, max_length=200, null=True)),
                ('device_type', models.CharField(blank=True, default='mobile', max_length=50, null=True)),
                ('device_os', models.CharField(blank=True, max_length=50, null=True)),
                ('device_version', models.CharField(blank=True, max_length=50, null=True)),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('updated_ts', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.userdevice'),
        ),
    ]
