# Generated by Django 3.1.2 on 2021-03-27 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210327_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_editor',
            field=models.BooleanField(default=False),
        ),
    ]
