# Generated by Django 3.1.2 on 2021-04-03 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_userprofile_is_editor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdevice',
            name='device_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
