# Generated by Django 3.1.2 on 2021-04-04 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_userprofile_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mobile_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
