from django.contrib import admin
from api.models import *

admin.site.register(UserProfile)
admin.site.register(HobbyCategory)
admin.site.register(Hobby)
admin.site.register(Raasi)
admin.site.register(EducationCategory)
admin.site.register(OccupationCategory)
admin.site.register(Star)
admin.site.register(MotherTongue)
admin.site.register(Religion)
admin.site.register(Caste)
admin.site.register(SubCaste)
admin.site.register(UserPhoto)
admin.site.register(Membership)
admin.site.register(UserDevice)
admin.site.register(Notification)
admin.site.register(RequestLogger)
admin.site.register(Message)
admin.site.register(MessageRoom)